
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import java.awt.Component;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author KAU
 */
public class Add_direction_to_new_roundabout_with_4_entries extends javax.swing.JFrame {

    DatabaseReference mDatabase;
    String id = "";
    static Account record;
    static Roundabout newrRoundabout;

    /**
     * Creates new form Add_direction_to_new_roundabout_with_4_entries
     */
    public Add_direction_to_new_roundabout_with_4_entries() {
        initComponents();

    }

    public Add_direction_to_new_roundabout_with_4_entries(Account record, Roundabout newRoundabout) {

        initComponents();
        Add_direction_to_new_roundabout_with_4_entries.record = record;
        Add_direction_to_new_roundabout_with_4_entries.newrRoundabout = newRoundabout;

        jLabel1.setText("User ID: " + record.getAccount_ID());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Button2 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        Button2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button2.setText("Back");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        jPanel2.add(Button2);
        Button2.setBounds(20, 423, 130, 40);

        Button1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button1.setText("Confirm");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        jPanel2.add(Button1);
        Button1.setBounds(699, 423, 130, 40);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(340, 450, 190, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Name of the street (South):");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(340, 430, 195, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Name of the street (East):");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(670, 230, 220, 20);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(680, 260, 160, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Name of the street (West):");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 220, 210, 14);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(10, 240, 170, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(470, 70, 150, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Name of the street (North):");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(270, 70, 270, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Please set the name of the streets in each direction as shown in the diagram:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 40, 665, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 115, 34);

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\downloads from chrome\\Traffic_Control_System_CPIT-499\\Photos\\roundabot.jpg")); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(190, 98, 476, 330);

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\downloads from chrome\\Traffic_Control_System_CPIT-499\\Photos\\1.jpg")); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 860, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean check_RoundaboutID() throws InterruptedException {
        Roundabout check = new Roundabout();
        mDatabase = FirebaseDatabase.getInstance().getReference().child("Database/Roundabouts/" + newrRoundabout.getRoundabout_ID() + "/roundabout_ID");

        mDatabase.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot ds) {
                // Get Post object and use the values to update the UI

                // temp_userID = ds.getChildren().toString();
                check.setRoundabout_ID(ds.getValue(String.class));
                // ...
            }

            @Override
            public void onCancelled(DatabaseError de) {

            }
        });
        Thread.sleep(6000);
        System.out.println(check.getRoundabout_ID()+"///   "+newrRoundabout.getRoundabout_ID());
        if (check.getRoundabout_ID() == null) {
            return true;
        } else if (check.getRoundabout_ID().equals(newrRoundabout.getRoundabout_ID())) {
            return false;
        } else {
            return true;
        }
    }
    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed

        try {
            newrRoundabout.North_street.setDir_name(jTextField1.getText());
            newrRoundabout.East_street.setDir_name(jTextField2.getText());
            newrRoundabout.South_street.setDir_name(jTextField3.getText());
            newrRoundabout.West_street.setDir_name(jTextField4.getText());
            
            newrRoundabout.North_street.setDistence(0);
            newrRoundabout.East_street.setDistence(0);
            newrRoundabout.South_street.setDistence(0);
            newrRoundabout.West_street.setDistence(0);
            
            newrRoundabout.North_street.setTraffic_light_status("red");
            newrRoundabout.East_street.setTraffic_light_status("red");
            newrRoundabout.South_street.setTraffic_light_status("red");
            newrRoundabout.West_street.setTraffic_light_status("red");
            
            
            
            if (check_RoundaboutID()) {
                mDatabase = FirebaseDatabase.getInstance().getReference().child("Database/Roundabouts/" + newrRoundabout.getRoundabout_ID());

                mDatabase.setValue(newrRoundabout, new DatabaseReference.CompletionListener() {
                    @Override
                    public void onComplete(DatabaseError de, DatabaseReference dr) {

                    }
                });
                Component frame = null;
                JOptionPane.showMessageDialog(frame,
                        "The roundabout has been added successfully ^_^");
                
                Main_menu_admin menu = new Main_menu_admin(record);
        menu.setVisible(true);
        this.setVisible(false);
            }else{
                Component frame = null;
            JOptionPane.showMessageDialog(frame,
                    "The roundabout ID is already exsist...",
                    "Wrong input",
                    JOptionPane.ERROR_MESSAGE);
            Add_new_roundabout anr = new Add_new_roundabout(record);
        anr.setVisible(true);
        this.setVisible(false);
            }

        } catch (InterruptedException ex) {

        }
    }//GEN-LAST:event_Button1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        Add_new_roundabout anr = new Add_new_roundabout(record);
        anr.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_Button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_direction_to_new_roundabout_with_4_entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_direction_to_new_roundabout_with_4_entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_direction_to_new_roundabout_with_4_entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_direction_to_new_roundabout_with_4_entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_direction_to_new_roundabout_with_4_entries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
