
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import static com.kingaspx.firebase.util.Common.initFirebase;
import java.awt.Component;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author KAU
 */
public class Create_account extends javax.swing.JFrame {
    
    private DatabaseReference mDatabase;
    private Account acc;
    static Account temp_account;
    String id = "";
    

    /**
     * Creates new form Create_account
     */
    public Create_account() throws IOException {
        initComponents();
    }

    Create_account(Account tempAccount) throws IOException {
        initComponents();
        temp_account = tempAccount;
        jLabel9.setText("User ID: " + tempAccount.getAccount_ID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Button2 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        CheckBox4 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Button2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button2.setText("Create");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        jPanel1.add(Button2);
        Button2.setBounds(550, 420, 140, 40);

        Button1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button1.setText("Back");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        jPanel1.add(Button1);
        Button1.setBounds(20, 423, 140, 40);

        CheckBox4.setText("Print report");
        CheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBox4);
        CheckBox4.setBounds(160, 360, 120, 23);

        CheckBox3.setText("Control the traffic");
        CheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBox3);
        CheckBox3.setBounds(160, 340, 120, 23);

        CheckBox2.setText("Modify the map");
        jPanel1.add(CheckBox2);
        CheckBox2.setBounds(160, 320, 120, 23);

        CheckBox1.setText("Create Accounts");
        jPanel1.add(CheckBox1);
        CheckBox1.setBounds(160, 300, 120, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Level of access:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 270, 150, 22);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(510, 220, 150, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Confirm password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 220, 148, 22);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(510, 180, 150, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Enter password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 180, 127, 22);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(510, 140, 150, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Phone number:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 140, 121, 22);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(170, 220, 150, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Enter last name:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 220, 129, 22);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(170, 180, 150, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Enter first name:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 180, 132, 22);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(170, 140, 150, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Enter user_ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 140, 130, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Account informaition");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 90, 190, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 10, 100, 40);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 270, 176, 46);

        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\downloads from chrome\\Traffic_Control_System_CPIT-499\\Photos\\1.jpg")); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 710, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        Main_menu_admin menu = new Main_menu_admin(temp_account);
        menu.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_Button1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void CheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox4ActionPerformed

    public void Check_for_duplicate_userID(String user_id) throws InterruptedException {
        //read_value(user_id);

        String password_after_checking = confirm_password(jPasswordField1.getText(), jPasswordField2.getText());
        privilage priv = new privilage();
        acc = new Account(jTextField1.getText(), jTextField2.getText(), jTextField3.getText(), password_after_checking,
                jTextField4.getText(), priv.get_privilage(CheckBox1.isSelected(), CheckBox2.isSelected(), CheckBox3.isSelected(), CheckBox4.isSelected()));

        if (check_userID(acc.getAccount_ID())) {
            if (password_after_checking != null) {

                mDatabase = FirebaseDatabase.getInstance().getReference().child("Database/accounts/" + acc.getAccount_ID());

                mDatabase.setValue(acc, new DatabaseReference.CompletionListener() {
                    @Override
                    public void onComplete(DatabaseError de, DatabaseReference dr) {

                    }
                });

                Component frame = null;
                JOptionPane.showMessageDialog(frame,
                        "The account has been created successfully ^_^");

            } else {
                Component frame = null;
                JOptionPane.showMessageDialog(frame,
                        "The password you have entered didn't match...",
                        "Wrong password",
                        JOptionPane.ERROR_MESSAGE);
            }

        } else {
            Component frame = null;
            JOptionPane.showMessageDialog(frame,
                    "The user ID is already exsist...",
                    "Wrong input",
                    JOptionPane.ERROR_MESSAGE);

        }

    }

    public String confirm_password(String first_password, String sec_password) {

        if (first_password.equals(sec_password)) {
            return sec_password;
        }

        return null;
    }

    public boolean check_userID(String user_id) throws InterruptedException {
        Account check_account = new Account();
        check_account.setAccount_ID("0");
        mDatabase = FirebaseDatabase.getInstance().getReference().child("Database/accounts/" + acc.getAccount_ID() + "/account_ID");

        mDatabase.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot ds) {
                // Get Post object and use the values to update the UI

                // temp_userID = ds.getChildren().toString();
                check_account.setAccount_ID(ds.getValue(String.class));
                // ...
            }

            @Override
            public void onCancelled(DatabaseError de) {

            }
        });
        Thread.sleep(6000);
        if (check_account.getAccount_ID() == null) {
            return true;
        } else if (check_account.getAccount_ID().equals(user_id)) {
            return false;
        } else {
            return true;
        }
    }

//    public String read_ID(String user_id) {
//        FirebaseDatabase database = FirebaseDatabase.getInstance();
//        DatabaseReference recive_id = database.getReference("Database/accounts/" + user_id + "/" + user_id);
//        recive_id.addValueEventListener(new ValueEventListener() {
//            @Override
//            public void onDataChange(DataSnapshot dataSnapshot) {
//
//                // This method is called once with the initial value and again
//                // whenever data at this location is updated.
//                String value = dataSnapshot.getValue(String.class);
//                System.out.println("i have got " + value);
//            }
//
//            @Override
//            public void onCancelled(DatabaseError error) {
//                // Failed to read value
//                System.out.println(error.toException().toString());
//            }
//        });
//        return value;//value from main class
//    }


    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed

        try {
            Check_for_duplicate_userID(jTextField1.getText());

        } catch (InterruptedException ex) {
            Logger.getLogger(Create_account.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button2ActionPerformed

    private void CheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Create_account().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Create_account.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
